export const env = {
  ELEVENLABS_API_KEY: process.env.NEXT_PUBLIC_ELEVENLABS_API_KEY,
  OPEN_AI_API_KEY: process.env.NEXT_PUBLIC_OPEN_AI_API_KEY,
  CAPTIONS_API_KEY: process.env.NEXT_PUBLIC_CAPTIONS_API_KEY,
};
